apiVersion: v1
kind: Namespace
metadata:
  name: chatbot-ui
---
apiVersion: v1
kind: Secret
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1na1UwR0tfTDBUd2xLN2pmMUNaekpJLU5DajJwU3p0UnRBb1I1OWRTbExIQncwNm05R0llczEwZy1BZHBDeGZqRF9QaGQ2dFNEVFQzQmxia0ZKckI1dmRrbVZOblhURGI0YW5rc0pfVVJUN1BPSjY4V3VQOW9RZmpGVm41Q0lIWWdaVGpOcG5HY1JRUFFXY2tWc2E4VDN0YUxnTUE=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          image: anji265400/chatbot-ui:latest  # Replace with actual Docker username
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-ui
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatbot-ui
  type: ClusterIP
